apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3-test-app
  labels:
    app: s3-test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s3-test-app
  template:
    metadata:
      labels:
        app: s3-test-app
    spec:
      containers:
      - name: s3-test-app
        image: quay.io/appvia/s3-test-app:v0.1.0
        ports:
          - containerPort: 3001
        env:
          - name: BUCKET_NAME
            valueFrom:
              secretKeyRef:
                name: eks-s3
                key: BUCKET_NAME
          - name: S3_REGION
            valueFrom:
              secretKeyRef:
                name: eks-s3
                key: S3_REGION
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: eks-s3
                key: S3_AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: eks-s3
                key: S3_AWS_SECRET_ACCESS_KEY
