apiVersion: app.appvia.io/v2beta1
kind: Application
metadata:
  name: testapp
spec:
  cloud: aws
  components:
  - cloudResource:
      plan: cloudposse-aws-s3-bucket
      variables:
        name: markappvia-20230413
    name: store
    type: CloudResource
  - container:
      env:
      - fromCloudResourceOutput:
          componentName: store
          output: ACCESS_KEY_ID
        name: AWS_ACCESS_KEY_ID
      - fromCloudResourceOutput:
          componentName: store
          output: SECRET_ACCESS_KEY
        name: AWS_SECRET_ACCESS_KEY
      - fromCloudResourceOutput:
          componentName: store
          output: USER_NAME
        name: USER_NAME
      - fromCloudResourceOutput:
          componentName: store
          output: BUCKET_REGION
        name: S3_REGION
      - fromCloudResourceOutput:
          componentName: store
          output: BUCKET_ID
        name: BUCKET_NAME
      expose: true
      image: quay.io/appvia/s3-test-app:v0.0.4
      port: 3001
      tls: true
    dependsOn:
    - store
    name: test
    type: Container
  name: testapp