apiVersion: app.appvia.io/v2beta1
kind: AppEnv
metadata: 
  name: aws-demo-dev
spec:
  name: dev
  stage: nonprod
  application: aws-demo
  cloud: aws
  clusterRef:
    group: compute.appvia.io
    kind: Cluster
    name: aks-d3c7e
    namespace: ws-demo
    version: v2beta1